### ISSUE TITLE
Major lag breaking blocks with MO 4.0 RC2 installed.

### ISSUE THREAD

**Issue by traikanossi** [simeonradivoev/MatterOverdrive#109]
Like the title says, when I break blocks, it takes them about 2 seconds to disappear (drop the block on the ground) after I finish breaking the block. This doesn't happen when I have MO 3.5 installed. Also, I did try to delete and regenerate the configs. It also seems to be intermittent. The lag disappears when restarting the game and loading an already made world.

I'm using Magic Launcher
Forge 10.13.4.1448-1.7.10

I have ~200 mods installed. Do you want the list?

**Comment by simeonradivoev** [comment]
Yes a list may help. Also more info about your system.

**Comment by traikanossi** [comment]
Windows 7 Home Premium 64-bit SP1
Java 1.8.0_45 64-bit
CPU: AMD FX-6300 Six Core 4.1GHz
RAM: 8GB DDR3
GPU: Sapphire R9 270 2GB

My FPS seems to be good. I am not sure what the exact FPS is, but the client runs smoothly in terms of graphics.

For your convenience, I've dropboxed the mods and configs.
https://www.dropbox.com/s/y3tj9yl3zj4b8f1/.minecraft.rar?dl=0
(As of the time of this writing, it's still syncing ETA 6 mins, so you might want to wait a few minutes before trying to download or open it.)

**Comment by simeonradivoev** [comment]
are all blocks from Matter Overdrive causing the lag. Are other mod's blocks causing a lag ?

**Comment by simeonradivoev** [comment]
I don't know how much testing you've done and how you can to the conclusion that Matter Overdrive is causing the lag, but I've just tested it with all you mods. The issue seems to occur mainly when a world is loaded for a second time without restarting minecraft. When i first enter a world, there is no visible lag. Furthermore the issue persists event if Matter Overdrive is now present.
