### ISSUE TITLE
Matter calculation from recipes appears broken

### ISSUE THREAD

**Issue by kotoroshinoto** [simeonradivoev/MatterOverdrive#249]
in a previous version I had matter values for things like bedrockium, but now i'm just getting zero for nearly everything.

What can cause this?

How do I force the mod to recalculate these values? Is there a config option, a direct command, etc?

**Comment by simeonradivoev** [comment]
Yes there is http://simeon.co.vu/Mods/MatterOverdrive/commands/. You can try and delete the registry file from the Matter Overdrive config folder.

**Comment by kotoroshinoto** [comment]
does it respond with a message that its doing its job? (Should I assume its doing the recalculation on SSP and SMP even if it doesn't say anything?)

**Comment by simeonradivoev** [comment]
You should check the logs.

**Comment by kotoroshinoto** [comment]
in the event that some items still show 0 matter after a recalc, how would I go about assessing why that might be?  (perhaps their components are all mod-items with no default value? Can I assign values to items that come from mods?)

**Comment by kotoroshinoto** [comment]
Perhaps you could have the load stage that handles the calculations identify the root-items for recipes that calculate to 0 and put them into a secondary config file? (does the calculation recurse through recipes to get all the values?) 

Does it only trace through crafting grid recipes or does it also look into smelting recipes? (I would imagine that mod-specific recipe types for processing machines probably aren't included)

**Comment by simeonradivoev** [comment]
The Matter calculation works by checking all recipes for an item. If all recipes for a certain item have a blacklisted or an item that cannot be replicated in it, then the items cannot be replicated as well. It's matter value becomes 0. On the other hand if the recipe consists of all replicateable items. Then the matter for that item is the sum of all items in it's recipe. The Calculation is done in passes. That means if an item is skipped in the first pass because it contains a non replicateable item in its recipe. It may in later passes have all of its recipe items, replicatable. There is also a Furnace calculation stage that works by copying the matter value from the item being smelted to the smelted one. The more recipes the item is used in, the better.
