### ISSUE TITLE
[suggestion] anomaly stabilizer improvement

### ISSUE THREAD

**Issue by shadoxxhd** [simeonradivoev/MatterOverdrive#385]
the inhibitor beams of the gravitational anomaly stabilizers should pierce through reactor controller and coil blocks in order to make big anomalies harvestable without the risk of the anomaly destroying the reactor.

**Comment by simeonradivoev** [comment]
You can put fusion reactors up to 3 blocks away from the anomaly. There is no need to allow for beams to pierce blocks. The occlusion of blocks is a added challenge.

**Comment by shadoxxhd** [comment]
can you place stabilizers inside the fusion ring? how big can the anomaly become without destroying a 3 block away fusion reactor, with 0/1/2/6 stabilizers?

**Comment by simeonradivoev** [comment]
you can place the stabilizes in a 64 block radius from the anomaly. Each stabiliser suppresses the anomaly by 30%.

**Comment by shadoxxhd** [comment]
now I'm confused. does the reactor block the suppression or not?

**Comment by simeonradivoev** [comment]
The gravitational stabilizers are not affected by the fusion reactor itself. They only need a clear line of sight to the anomaly. Any solid block including the fusion reactor controller, or machine hulls or coils, or any other solid block, stops the stabilizers from working, because it blocks it's line of sight to the anomaly. You can use transparent blocks (any type of glass even Tritanium glass) and they will not stop the stabilizer beam.

**Comment by shadoxxhd** [comment]
can i use tritanium glass instead of the fusion coils in the reactor ring then?

**Comment by simeonradivoev** [comment]
No

**Comment by shadoxxhd** [comment]
does the reactor work when i place blocks inside the ring (stabilizers or (possibly transparent) isolation materials)?

**Comment by simeonradivoev** [comment]
Why don't you try it out? The fusion reactor is not affected by any blocks inside the ring.

**Comment by shadoxxhd** [comment]
thx for the info. looks like this suggestion is mostly meaningless under then.
