### ISSUE TITLE
Client side crash

### ISSUE THREAD

**Issue by cauliflower69** [simeonradivoev/MatterOverdrive#435]
After the server crash issue I posted earlier I set the forge.cfg to remove erroring items. Now the clients are getting crashes with this report 

http://pastebin.com/NjK4uhDM

I wasn't sure if the two were connected so I made a new issue

**Comment by Badcholo** [comment]
You don't want to have forge remove erroring entities. That will in the end cause players to all of a sudden lose items from their inventory or even items they are holding will just magically disappear. 
I would suggest you fix the errors and / or remove the mod causing the issues. It would also cause crashing since players are attempting to log in with items that don't exist anymore or blocks that were placed or are in use.

**Comment by Badcholo** [comment]
Also fastcraft seems to be a root cause for a lot of crashing and errors, just like optifine. 
I would remove that mod and see if you still have the issue.

**Comment by simeonradivoev** [comment]
No the issue is not connected to that.

**Comment by cauliflower69** [comment]
Ahhh I was just replying also. Ninja'd

**Comment by Badcholo** [comment]
it may not be causing the issue, but that setting for forge will cause some problems later.
I don't have much experience with fastcraft, just comments about it causing issues.

**Comment by shadowfacts** [comment]
1) 1.7.10 isn't supported anymore 2) possibly caused by FastCraft
