### ISSUE TITLE
Mad scientist not spawning

### ISSUE THREAD

**Issue by gp009** [simeonradivoev/MatterOverdrive#462]
Brief explanation of problem: Mad scientist not anywhere to be found

Steps to reproduce:visit ANY village

Crash report paste (if any) on [gist](gist.github.com):

MatterOverdrive version:0.4.1

Minecraft version:1.7.10

**Comment by simeonradivoev** [comment]
They spawn I've seen them myself.

**Comment by ajthemacboy** [comment]
They're pretty rare from what I've seen. On most of my servers with MO players have complained about being too hard to find, so I usually just place one in a cage near spawn.

**Comment by 63502** [comment]
I have experienced this also. Since I have the witchery mod installed, NPC villages in my worlds(vanilla, superflat overworld and desert type, and ATG generated worlds have significantly increased village generation rate and base size, the number of Matter Overdrive houses without mad scientists is obvious. 

I would definitely consider this a bug, as I have done creative mode searches through many villages in multiple overworld type superflat worlds, and even then in an ideal village environment with plenty of MO houses to spare, there are no signs of naturally generated Mad Scientists at all.

If they do spawn naturally, they do so at an excessively low rate that is simply impractical to pure survival game-play. I would suggest at very least increasing their spawn rate in villages so as to include at least one per house generated.

**Comment by Alexismachina** [comment]
They spawn in villages , only in their respective buildings.

**Comment by 63502** [comment]
I know that they are supposed to, the problem is that they don't. I mentioned this above, but I explored 60+ villages in superflat overworld with heightened village frequency and size, and none of the sometimes multiple MO houses in any of these villages had mad scientists.

**Comment by kurokuno** [comment]
same issue can never find any no matter how much i look did over 200 + villages using draconic flight and never anywhere in there building/the entire village

**Comment by shadowfacts** [comment]
See #561
