### ISSUE TITLE
Crash while runnning compiled mod from source

### ISSUE THREAD

**Issue by IronworksProductions** [simeonradivoev/MatterOverdrive#610]
I forked your project tried to build in intellij idea. IDEA can't find net.minecraft classes so all of that failed. But building from command line worked. Then tested the built mod on a clean server and it crashed with this error:https://hastebin.com/eyuyociliv.sql
Also travis-ci failed building it as well despite numerous attempts.

any idea what could cause it?

--
NN

**Comment by shadowfacts** [comment]
1. MO is a Forge project and has to be setup as such. See [here](http://mcforge.readthedocs.io/en/latest/gettingstarted/) for intructions on how to load a Forge project into your IDE.
2. The 1.10.2 version of MO is buggy and broken. The crash is caused by a client class being referenced on a dedicated server.

If you're attempting to build MO for use in a playthrough, I highly recommend against it. MO for 1.10.2 is buggy and is almost completely untested.

**Comment by IronworksProductions** [comment]
Ok i followed those instructions and  ran it and got this:Error:(34, 28) java: package net.minecraft.client does not exist, Error:(35, 35) java: package net.minecraft.entity.player does not exist

**Comment by shadowfacts** [comment]
¯\_(ツ)_/¯

You must have done something wrong, those instructions are correct.

**Comment by Muirrum** [comment]
@nacjm IntelliJ IDEA has a finicky setup, try using eclipse

**Comment by IronworksProductions** [comment]
Yeah I tested eclipse now and it works IDEA seems not to function or its because I typed in the commands with the project already open in idea

I have learned that Eclipse CHE also hits a wall when trying to get it to function for mod development.

**Comment by Muirrum** [comment]
Well, I still haven't been able to get Che to work for anything at all
